/**
 * Azure OpenAI client service.
 * Provides code explanation functionality using Azure OpenAI.
 */

import OpenAI from 'openai';
import { config } from '../config/env';
import type { ExplainRequest } from '@ghia-ai/shared';

/**
 * Singleton Azure OpenAI client instance.
 */
const client = new OpenAI({
  apiKey: config.AZURE_OPENAI_API_KEY,
  baseURL: `${config.AZURE_OPENAI_ENDPOINT}/openai/deployments/${config.AZURE_OPENAI_DEPLOYMENT}`,
  defaultQuery: { 'api-version': config.AZURE_OPENAI_API_VERSION },
  defaultHeaders: { 'api-key': config.AZURE_OPENAI_API_KEY }
});

/**
 * Generates a code explanation using Azure OpenAI.
 * @param request - The explanation request containing code, language, and optional context
 * @returns The generated explanation text
 * @throws Error if the Azure OpenAI API call fails
 */
export async function generateExplanation(request: ExplainRequest): Promise<string> {
  const detailLevel = request.detailLevel || 'brief';

  // Build system prompt based on detail level
  const systemPrompt = detailLevel === 'brief'
    ? 'You are a code explanation assistant. Provide a concise, beginner-friendly explanation of the following code. Focus on what it does and why.'
    : 'You are a code explanation assistant. Provide a comprehensive explanation of the following code, including what it does, how it works, and why certain approaches were used.';

  // Build user message with code, language, and optional context
  let userMessage = `Language: ${request.language}\n\nCode:\n${request.code}`;

  if (request.context) {
    userMessage += `\n\nContext:\n${request.context}`;
  }

  if (request.fileStructure) {
    userMessage += `\n\nFile Structure:\n${request.fileStructure}`;
  }

  try {
    const response = await client.chat.completions.create({
      model: config.AZURE_OPENAI_DEPLOYMENT,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userMessage }
      ],
      temperature: 0.7,
      max_tokens: detailLevel === 'brief' ? 500 : 1500
    });

    const explanation = response.choices[0]?.message?.content;

    if (!explanation) {
      throw new Error('No explanation generated by Azure OpenAI');
    }

    return explanation;
  } catch (error) {
    // Re-throw the error to be handled by the caller
    throw error;
  }
}
